const fs = require('fs');

const scriptDirectory = './scripts';

//i tried my darnest to use one regex but for some reason it wouldn't catch the imports properly. encoding?
const importFileRegex = /imports\.js$/g;
const exportFileRegex = /exports\.js$/g;

const buildPath = './static/build';

if(!fs.existsSync(buildPath)){
    fs.mkdirSync(buildPath);
}

console.log('This build file creates nice static javascript files for use as modules without having to write all the code twice');

console.log('Adds .import.js file to start');
console.log('Adds .export.js file to end');

console.log('Dependecy reslution is manual :(');
console.log('*******************************\n\n');

fs.readdir(scriptDirectory, (err, files) => {

    if(err)
    {
        console.error(err);
        return;
    }

    files.forEach(file => {
        
        if(exportFileRegex.test(file) || importFileRegex.test(file))
            return;

        let scriptFileName = `${scriptDirectory}/${file}`;

        console.log(`Checking: ${scriptFileName}`);

        let dotPosition = file.lastIndexOf('.');

        let fileWithoutExt = file.substring(0, dotPosition);
        let exportFileName = `${scriptDirectory}/${fileWithoutExt}.exports.js`;
        let importFileName = `${scriptDirectory}/${fileWithoutExt}.imports.js`;
        
        let importContent = '';
        let exportContent = '';

        if(fs.existsSync(exportFileName)){
            exportContent = fs.readFileSync(exportFileName);
            console.log('\tHas Export File');
        }

        if(fs.existsSync(importFileName)){
            importContent = fs.readFileSync(importFileName);
            console.log('\tHas Import File');
        }

        let combinedFile = '//***AUTOGENERATED BUILD FILE****\n' 
            + importContent + '\n' 
            + fs.readFileSync(scriptFileName) + '\n' 
            + exportContent;

        let newBuildFileName = `${buildPath}/${fileWithoutExt}.js`;

        try
        {
            fs.writeFileSync(newBuildFileName, combinedFile);
            console.log(`\tcreated new build file: ${newBuildFileName}`);
        }
        catch(err)
        {
            console.error(err);
        }

    });

    console.log('\n\n***************\nDone! Static files built and ready to serve');
});


