const fs = require('fs');

const scriptDirectory = './scripts';

//i tried my darnest to use one regex but for some reason it wouldn't catch the imports properly. encoding?
const importFileRegex = /imports\.js$/g;
const exportFileRegex = /exports\.js$/g;

const buildPath = './static/build';

if(!fs.existsSync(buildPath)){
    fs.mkdirSync(buildPath);
}

fs.readdir(scriptDirectory, (err, files) => {

    if(err)
    {
        console.error(err);
        return;
    }

    files.forEach(file => {
        
        if(exportFileRegex.test(file) || importFileRegex.test(file))
            return;

        let scriptFileName = `${scriptDirectory}/${file}`;

        console.log(`Checking: ${scriptFileName}`);

        let dotPosition = file.lastIndexOf('.');

        let fileWithoutExt = file.substring(0, dotPosition);
        let exportFileName = `${scriptDirectory}/${fileWithoutExt}.exports.js`;
        let importFileName = `${scriptDirectory}/${fileWithoutExt}.imports.js`;
        
        let importContent = '';
        let exportContent = '';

        if(fs.existsSync(exportFileName)){
            exportContent = fs.readFileSync(exportFileName);            
        }

        if(fs.existsSync(importFileName)){
            importContent = fs.readFileSync(importFileName);            
        }

        let combinedFile = '//***AUTOGENERATED BUILD FILE****\n' 
            + importContent + '\n' 
            + fs.readFileSync(scriptFileName) + '\n' 
            + exportContent;

        fs.writeFile(`${buildPath}/${fileWithoutExt}.js`, combinedFile, err =>
        {
            if(err)
                console.log(err);
            else
            {
                console.log('created new build file');
            }
        });

    });
});